/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectcarobyhd.FileGoc;

import projectcarobyhd.FileGoc.Game15x15.view.App1515;
import projectcarobyhd.FileGoc.Game20x20.view.App2020;
import projectcarobyhd.FileGoc.Game9x9.view.App99;
import projectcarobyhd.FileGoc.GameMxM.view.AppMxM;


/**
 *
 * @author HUY DUNG
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gioithieu = new javax.swing.JDialog();
        Email = new javax.swing.JLabel();
        NguoiLapTrinh = new javax.swing.JLabel();
        NgayPhatHanh = new javax.swing.JLabel();
        PhienBan = new javax.swing.JLabel();
        CapPhep = new javax.swing.JLabel();
        NgayCap = new javax.swing.JLabel();
        CTy = new javax.swing.JLabel();
        DiaChi = new javax.swing.JLabel();
        AnhNenGT = new javax.swing.JLabel();
        Nguoichoichon = new javax.swing.JDialog();
        Chonbando = new javax.swing.JLabel();
        Luotdi = new javax.swing.JComboBox<>();
        Batdauchoi = new javax.swing.JButton();
        AnhNenGDC = new javax.swing.JPanel();
        GioiThieu = new javax.swing.JButton();
        NguoivsMay = new javax.swing.JButton();
        Thoat = new javax.swing.JButton();
        MayvsMay = new javax.swing.JButton();
        AnhNen = new javax.swing.JLabel();

        Gioithieu.setTitle("Giới thiệu");
        Gioithieu.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Email.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Email.setText("E-mail: dungb1906445@student.ctu.edu.vn");
        Gioithieu.getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 480, 50));

        NguoiLapTrinh.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NguoiLapTrinh.setText("Người lập trình: Nguyễn Huỳnh Huy Dũng");
        Gioithieu.getContentPane().add(NguoiLapTrinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 480, 50));

        NgayPhatHanh.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NgayPhatHanh.setText("Ngày phát hành: 5/11/2022");
        Gioithieu.getContentPane().add(NgayPhatHanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 480, 50));

        PhienBan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        PhienBan.setText("Phiên bản (version) : 1.0");
        Gioithieu.getContentPane().add(PhienBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 480, 50));

        CapPhep.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        CapPhep.setText("Sản phẩm được cấp phép sử dụng cho:");
        Gioithieu.getContentPane().add(CapPhep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 480, 50));

        NgayCap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        NgayCap.setText("Ngày cấp phép: 5/11/2022");
        Gioithieu.getContentPane().add(NgayCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 480, 50));

        CTy.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CTy.setText("Công ty: Trường Đại học Cần Thơ");
        Gioithieu.getContentPane().add(CTy, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 480, 50));

        DiaChi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DiaChi.setText("Địa chỉ: Khu II, Đ. 3/2, Xuân Khánh, Ninh Kiều, Cần Thơ");
        Gioithieu.getContentPane().add(DiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 480, 50));

        AnhNenGT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcarobyhd/FileGoc/image/AnhNenGT.png"))); // NOI18N
        Gioithieu.getContentPane().add(AnhNenGT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Nguoichoichon.setTitle("Người chơi chọn lượt đi");

        Chonbando.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Chonbando.setText("Chọn bản đồ");

        Luotdi.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Luotdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9x9", "15x15", "20x20" }));
        Luotdi.setSelectedIndex(-1);
        Luotdi.setToolTipText("");
        Luotdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuotdiActionPerformed(evt);
            }
        });

        Batdauchoi.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Batdauchoi.setText("Bắt đầu chơi");
        Batdauchoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BatdauchoiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NguoichoichonLayout = new javax.swing.GroupLayout(Nguoichoichon.getContentPane());
        Nguoichoichon.getContentPane().setLayout(NguoichoichonLayout);
        NguoichoichonLayout.setHorizontalGroup(
            NguoichoichonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NguoichoichonLayout.createSequentialGroup()
                .addGroup(NguoichoichonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NguoichoichonLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(NguoichoichonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Batdauchoi, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Chonbando)))
                    .addGroup(NguoichoichonLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(Luotdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        NguoichoichonLayout.setVerticalGroup(
            NguoichoichonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NguoichoichonLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Chonbando)
                .addGap(44, 44, 44)
                .addComponent(Luotdi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Batdauchoi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        Luotdi.getAccessibleContext().setAccessibleName("Lượt đi");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Cờ Caro");
        setBackground(new java.awt.Color(0, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(652, 652));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AnhNenGDC.setOpaque(false);

        javax.swing.GroupLayout AnhNenGDCLayout = new javax.swing.GroupLayout(AnhNenGDC);
        AnhNenGDC.setLayout(AnhNenGDCLayout);
        AnhNenGDCLayout.setHorizontalGroup(
            AnhNenGDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        AnhNenGDCLayout.setVerticalGroup(
            AnhNenGDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(AnhNenGDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        GioiThieu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        GioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcarobyhd/FileGoc/image/info.png"))); // NOI18N
        GioiThieu.setText("Giới Thiệu");
        GioiThieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GioiThieuMouseClicked(evt);
            }
        });
        getContentPane().add(GioiThieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        GioiThieu.getAccessibleContext().setAccessibleName("GioiThieu");

        NguoivsMay.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NguoivsMay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcarobyhd/FileGoc/image/humanvsbot.png"))); // NOI18N
        NguoivsMay.setText("Người với máy"); // NOI18N
        NguoivsMay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NguoivsMayMouseClicked(evt);
            }
        });
        getContentPane().add(NguoivsMay, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 260, -1));
        NguoivsMay.getAccessibleContext().setAccessibleDescription("");

        Thoat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcarobyhd/FileGoc/image/logout.png"))); // NOI18N
        Thoat.setText("Thoát");
        Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatActionPerformed(evt);
            }
        });
        getContentPane().add(Thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));
        Thoat.getAccessibleContext().setAccessibleName("Thoat");

        MayvsMay.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        MayvsMay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcarobyhd/FileGoc/image/bot.png"))); // NOI18N
        MayvsMay.setText("Máy với máy");
        MayvsMay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MayvsMayMouseClicked(evt);
            }
        });
        getContentPane().add(MayvsMay, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 250, -1));

        AnhNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectcarobyhd/FileGoc/image/AnhNenGDC.png"))); // NOI18N
        AnhNen.setAlignmentX(0.5F);
        AnhNen.setMaximumSize(new java.awt.Dimension(652, 652));
        AnhNen.setMinimumSize(new java.awt.Dimension(652, 652));
        AnhNen.setPreferredSize(new java.awt.Dimension(652, 652));
        getContentPane().add(AnhNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        AnhNen.getAccessibleContext().setAccessibleName("AnhNen");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ThoatActionPerformed

    private void BatdauchoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BatdauchoiMouseClicked
        if(Luotdi.getSelectedItem().equals("9x9")){
            App99 a = new App99();
            a.setVisible(true);
            Nguoichoichon.setVisible(false);
            
        }
        else if(Luotdi.getSelectedItem().equals("15x15")){
            App1515 a = new App1515();
            a.setVisible(true);
            Nguoichoichon.setVisible(false);
        } else if(Luotdi.getSelectedItem().equals("20x20")){
            App2020 a = new App2020();
            a.setVisible(true);
            Nguoichoichon.setVisible(false);
        } 
    }//GEN-LAST:event_BatdauchoiMouseClicked

    private void NguoivsMayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NguoivsMayMouseClicked
        Nguoichoichon.setSize(400, 400);
        Nguoichoichon.setTitle("Chọn bản đồ");
        Nguoichoichon.setLocationRelativeTo(null);
        Nguoichoichon.setVisible(true);
        dispose();
    }//GEN-LAST:event_NguoivsMayMouseClicked

    private void LuotdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuotdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LuotdiActionPerformed

    private void MayvsMayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MayvsMayMouseClicked
        AppMxM a = new AppMxM();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_MayvsMayMouseClicked

    private void GioiThieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GioiThieuMouseClicked
        Gioithieu.setSize(530, 557);
        Gioithieu.setTitle("Thông tin trò chơi");
        Gioithieu.setLocationRelativeTo(null);
        Gioithieu.setVisible(true);
    }//GEN-LAST:event_GioiThieuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnhNen;
    private javax.swing.JPanel AnhNenGDC;
    private javax.swing.JLabel AnhNenGT;
    private javax.swing.JButton Batdauchoi;
    private javax.swing.JLabel CTy;
    private javax.swing.JLabel CapPhep;
    private javax.swing.JLabel Chonbando;
    private javax.swing.JLabel DiaChi;
    private javax.swing.JLabel Email;
    private javax.swing.JButton GioiThieu;
    private javax.swing.JDialog Gioithieu;
    private javax.swing.JComboBox<String> Luotdi;
    private javax.swing.JButton MayvsMay;
    private javax.swing.JLabel NgayCap;
    private javax.swing.JLabel NgayPhatHanh;
    private javax.swing.JLabel NguoiLapTrinh;
    private javax.swing.JDialog Nguoichoichon;
    private javax.swing.JButton NguoivsMay;
    private javax.swing.JLabel PhienBan;
    private javax.swing.JButton Thoat;
    // End of variables declaration//GEN-END:variables
}
